import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useMetamask, useAddress, useEditionDrop } from "@thirdweb-dev/react";

export default function Home() {
  const connectWithMetamask = useMetamask();
  const address = useAddress();
  const editionDrop = useEditionDrop("0x270eDec8324F54Dda71224BDc8E8492206d4232b");
  const tokenId = 0;
  const quantity = 1;

  const claimNFT = async () => {
    try {
      await editionDrop?.claimTo(address, tokenId, quantity);
      console.log("🎉 NFT claimed successfully!");
    } catch (err) {
      console.log("💩 Error claiming NFT: ", err);
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className={styles.main}>
        <div className={styles.container}>
          {address ? (
            <>
            <h2>You are signed in as {address}</h2>
            <button onClick={claimNFT}>Claim NFT</button>
            </>
          ) : (
            <button onClick={connectWithMetamask}>Sign in with metamask</button>
          )}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
          <span> |& El Ducati</span>
        </a>
      </footer>
    </div>
  )
}
